### ISSUE TITLE
Change Keywords field to be mandatory

### ISSUE THREAD

**Issue by danielpetty** [denverpost/video-files#1]
Move Keywords field into the "mandatory" section. 

If possible, add this text for ad tags:

dpnews - any news video without Molly
dpent - any entertainment video without Molly
dptvmolly - anything with Molly
sportsshow - anything from The Sports Show
dpmarijuana - anything about marijuana
cannabistfull - the full episode of The Cannabist Show
culturs - any Culturs video (you will probably never use this)

**Comment by freejoe76** [comment]
Fixed
